name: Devops workflow

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Aplication
      run: echo "Building the application..."

  dev: 
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Dev
      run: echo "Deploying to development environment..."

  qa: 
    runs-on: ubuntu-latest
    needs: 
      dev

    steps:
    - name: Deploy to QA
      run: echo "Deploying to QA environment..."

  uat: 
    runs-on: ubuntu-latest
    needs: 
      qa

    steps:
    - name: Deploy to UAT
      run: echo "Deploying to UAT environment..."

  prod: 
    runs-on: ubuntu-latest
    needs: uat  

    steps:
    - name: Deploy to Prod
      run: echo "Deploying to production environment..."
  


    
      